# docker-compose.ml
dc-campaign-ui:
  build: .
  ports:
  - "80:3000"
  - "3001:3001"
  volumes:
  - .:/usr/src/dc-campaign-finance-watch
  environment:
  - NODE_ENV=dev
  command: sh -c 'npm install && npm run serve'
