version: '2'
services:
  web:
    build: .
    ports:
    - "3001:3001"
    depends_on:
    - api
    environment:
    - REACT_WEBPACK_ENV=dev
  redis:
    image: redis
    ports:
    - "6379:6379"
    command: [redis-server]
  db:
    image: mongo:3.2
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
    - "8000:8000"
    - "8001:8001"
    depends_on:
    - db
    - redis
