FROM  mongo:3.2

RUN mongorestore --host mongodb:27017 --drop dc-campaign-finance-mongodatabase
RUN unzip dc-campaign-finance-mongodatabase.zip -d dc-campaign-finance-mongodatabase
CMD ["mongorestore", "--host","mongodb:27017","--drop", "./dc-campaign-finance-mongodatabase"]

CMD ["./scripts/wait-for-it.sh","mongodb:27017"]

# could the the wait for be replaced until the health check, could remove wait-for-it.sh
# research RUN and how it interacts with the image
# shouldn't commands run?
