FROM  mongo:3.2

COPY dc-campaign-finance-mongodatabase.zip .

# update packages and intall unzip
RUN apt-get update
RUN apt-get install unzip

# unzip db .bson files to root dir
RUN unzip dc-campaign-finance-mongodatabase.zip -d .

# restore mongodb using docker compose name
CMD mongorestore --host mongodb -d dc-campaign-finance --drop ./dc-campaign-finance-mongodatabase/dc-campaign-finance
