version: '2'
services:
  web:
    build: .
    ports:
    - "3001:3001"
    environment:
    - REACT_WEBPACK_ENV=dev
  redis:
    image: redis
    ports:
    - "6379"
    command: [redis-server]
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    ports:
    - "27017:27017"
  mongo-seed:
    build:
      context: .
      dockerfile: Dockerfile-mongo-seed
    links:
     - mongodb
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
    - "8000:8000"
    - "8001:8001"
    links:
    - mongodb
    - redis
